library(dplyr)
data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
data <- dplyr::filter(data, Date %in% c("1/2/2007", "2/2/2007"))
png(file = "plot2.png", width = 480, height = 480)
plot(strptime(paste(data$Date, data$Time, sep = " "), "%d/%m/%Y %H:%M:%S"), data$Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
dev.off()
